### ISSUE TITLE
Property 'UpdateBoxOptions' does not exist on type 'typeof MeshBuilder'

### ISSUE THREAD

**Issue by AyoubCSC** [JSGirald/ionic-babylon#2]
Hi,

I'm getting the following error:

`Property 'UpdateBoxOptions' does not exist on type 'typeof MeshBuilder'`

when trying to compile in device. The error is in Home.ts:

```
ionViewWillEnter() {
    if (this.config.hasChanged) { // has anything changed?
      // then reset uv settings for both dice
      let options = {
        size: 1.25,
        faceUV: this.config.getFaceUV(this.config.colorOne),
        updatable: false
      }
      MeshBuilder.UpdateBoxOptions(this.firstDie, options);

      options = {
        size: 1.25,
        faceUV: this.config.getFaceUV(this.config.colorTwo),
        updatable: false
      }
      MeshBuilder.UpdateBoxOptions(this.secondDie, options);
    }
  }
```
version of BabylonJS 2.5.0

**Comment by JSGirald** [comment]
Hi, thanks for pointing this out. Actually I pushed some experimental stuff to master instead of branching. I'll sort It out as soon as I can.

**Comment by JSGirald** [comment]
I have reverted all references to UpdateBoxOptions, it should work ok now.
The branch 'experimental' contains stuff that only works under certain setup.
Let me know if it works for you. Thx

**Comment by AyoubCSC** [comment]
Hi again :), i noticed that it cant load `cannon.min.js` and `babylon.js`. So i moved them to `assets/js/babylon.js` and `assets/js/cannon.min.js` and i changed index.html to `<script src="assets/js/babylon.js"></script>` and `<script src="assets/js/cannon.min.js"></script>` and now it work fine :). Thanks for your help and your time.
